general {
    lock_cmd = pidof hyprlock || hyprlock       # evita iniciar múltiplas instâncias do hyprlock.
    before_sleep_cmd = loginctl lock-session    # bloqueia a sessão antes do PC entrar em suspensão.
    after_sleep_cmd = hyprctl dispatch dpms on  # garante que o monitor liga após acordar.
}

# 1. Escurecer a tela (Poupe bateria)
listener {
    timeout = 150                                 # 2.5 min.
    on-timeout = brightnessctl set 10%            # reduz o brilho do monitor para 10%.
    on-resume = brightnessctl set 100%            # restaura o brilho ao mexer no rato/teclado.
}

# 2. Bloquear o ecrã com a tua vaquinha
listener {
    timeout = 300                                 # 5 min.
    on-timeout = loginctl lock-session            # ativa o hyprlock.
}

# 3. Desligar o monitor (DPMS)
listener {
    timeout = 330                                 # 5.5 min.
    on-timeout = hyprctl dispatch dpms off        # desliga o ecrã.
    on-resume = hyprctl dispatch dpms on          # liga o ecrã de volta ao detetar atividade.
}

# 4. Suspensão total do PC (Suspend)
listener {
    timeout = 1800                                # 30 min.
    on-timeout = systemctl suspend                # mete o portátil a dormir.
}
