source = $HOME/.config/hypr/mocha.conf

$accent = $mauve
$accentAlpha = $mauveAlpha
$font = JetBrainsMono Nerd Font

# GENERAL
general {
    disable_loading_bar = true
    hide_cursor = true
    no_fade_in = false
    no_fade_out =false
    enable_shadow = false



}

# BACKGROUND
background {
    monitor =
    color = rgba(0, 0, 0, 1.0)
  
}

# TIME
label {
    monitor =
    text = cmd[update:120000] fortune | cowsay
    color = rgba (255, 255, 255, 1.0)
    font_size = 16
    font_family = Monospace
    position = 0, 80
    halign = center
    valign = center
  

}

# DATE 
label {
    monitor = 
    text = cmd[update:60000] echo "$(date +"%A, %d %B %Y")"
    color = rgba(150, 150, 150, 1.0)
    font_size = 11
    font_family = JetBrainsMono Nerd Font
    position = 20, -20
    halign = left
    valign = top
    

}

# USER AVATAR

image {
    monitor = 
    path = ~/.face
    size = 100
    border_color = $accent

    position = 0, 75
    halign = center
    valign = center
}

# INPUT FIELD
input-field {
    monitor =
    size = 0, 0
    outline_thickness = 0
    dots_size = 0
    dots_spacing = 0
    dots_center = true
    fade_on_empty = false
    placeholder_text =
    hide_input = true
    position = 0, 0
    halign = center
    valign = center    


}
